events {
    worker_connections 1024;
}

http {
    server {
        listen 443 ssl;
        server_name _;

        ssl_certificate /etc/ssl/certs/railway.crt;      # Railway خودکار تزریق می‌کند
        ssl_certificate_key /etc/ssl/private/railway.key; # Railway خودکار تزریق می‌کند

        location /saeedsecrettss {   # مسیر WebSocket شما (دقیقاً مطابق پنل 3X-UI)
            proxy_pass https://84.200.205.210:443;       # آی‌پی Ultahost
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host vpn.saeedcloud.shop;  # نام دامنه‌ای که سرور اصلی می‌شناسد
            proxy_set_header X-Real-IP $remote_addr;
            proxy_ssl_verify off;                         # گواهی خودامضا را قبول کند
        }
    }
}